"""RunPod handler for the VACE inpainting worker.

The stock ``worker-comfyui`` handler is image-only.  This handler keeps its
ComfyUI startup process but accepts the API's small job contract, downloads a
source video, expands the official UI workflow to a ComfyUI API prompt and
returns the MP4 generated by ``SaveVideo`` as base64.
"""

from __future__ import annotations

import base64
import json
import os
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import requests
import runpod


COMFY_URL = "http://127.0.0.1:8188"
COMFY_INPUT = Path("/comfyui/input")
WORKFLOW_PATH = Path("/opt/vace/official-vace-inpainting.workflow.json")
VOLUME_MODELS = Path("/runpod-volume/models")
SAM3_FILENAME = "sam3.1_multiplex_fp16.safetensors"
SAM3_URL = (
    "https://huggingface.co/Comfy-Org/sam3.1/resolve/main/checkpoints/"
    f"{SAM3_FILENAME}"
)
MAX_INPUT_BYTES = 100 * 1024 * 1024
SERVER_START_TIMEOUT_SECONDS = 600
EXECUTION_TIMEOUT_SECONDS = 3_500
CONTROL_WIDGET_VALUES = {"fixed", "increment", "decrement", "randomize"}


@dataclass(frozen=True)
class NodeOutput:
    node_id: str
    slot: int


class WorkflowFlattener:
    """Expand LiteGraph subgraphs and serialize nodes for ComfyUI's /prompt API."""

    def __init__(self, workflow: dict[str, Any], object_info: dict[str, Any]):
        self.workflow = workflow
        self.object_info = object_info
        self.subgraphs = {
            graph["id"]: graph for graph in workflow.get("definitions", {}).get("subgraphs", [])
        }
        self.result: dict[str, dict[str, Any]] = {}
        self.expanded_subgraphs: dict[str, dict[int, NodeOutput | None]] = {}

    def flatten(self) -> dict[str, dict[str, Any]]:
        self._expand(self.workflow, "", {})
        return self.result

    @staticmethod
    def _node_id(path: str, node_id: int) -> str:
        return str(node_id) if not path else f"{path}/{node_id}"

    @staticmethod
    def _link_map(graph: dict[str, Any]) -> dict[int, tuple[int, int, int, int]]:
        links: dict[int, tuple[int, int, int, int]] = {}
        for link in graph.get("links", []):
            if isinstance(link, list):
                link_id, source_id, source_slot, target_id, target_slot = link[:5]
            else:
                link_id = link["id"]
                source_id = link["origin_id"]
                source_slot = link["origin_slot"]
                target_id = link["target_id"]
                target_slot = link["target_slot"]
            links[int(link_id)] = (int(source_id), int(source_slot), int(target_id), int(target_slot))
        return links

    @staticmethod
    def _widget_values(node: dict[str, Any]) -> list[Any]:
        values = node.get("widgets_values", [])
        if values is None:
            return []
        return values if isinstance(values, list) else [values]

    @staticmethod
    def _uses_widget(input_config: Any) -> bool:
        """Return whether a ComfyUI API input consumes a UI widget value."""
        if not isinstance(input_config, (list, tuple)) or not input_config:
            return False
        kind = input_config[0]
        if isinstance(kind, (list, tuple)):
            return True  # COMBO options are serialized as a list.
        if kind in {"INT", "FLOAT", "STRING", "BOOLEAN", "COMBO", "NUMBER"}:
            return True
        if len(input_config) > 1 and isinstance(input_config[1], dict):
            return any(
                key in input_config[1]
                for key in ("default", "min", "max", "step", "multiline")
            )
        return False

    def _expand(
        self,
        graph: dict[str, Any],
        path: str,
        bindings: dict[int, NodeOutput | None],
    ) -> dict[int, NodeOutput | None]:
        if path in self.expanded_subgraphs:
            return self.expanded_subgraphs[path]

        nodes = {int(node["id"]): node for node in graph.get("nodes", [])}
        links = self._link_map(graph)
        input_node_id = int(graph.get("inputNode", {}).get("id", -10))
        output_node_id = int(graph.get("outputNode", {}).get("id", -20))
        expanded_children: dict[int, dict[int, NodeOutput | None]] = {}

        def source_for_link(link_id: int | None) -> NodeOutput | None:
            if link_id is None or int(link_id) not in links:
                return None
            source_id, source_slot, _, _ = links[int(link_id)]
            if source_id == input_node_id:
                return bindings.get(source_slot)
            source_node = nodes[source_id]
            source_type = source_node.get("type")
            if source_type in self.subgraphs:
                child = expanded_children.get(source_id)
                if child is None:
                    child_bindings: dict[int, NodeOutput | None] = {}
                    parent_inputs = {
                        item.get("name"): item
                        for item in source_node.get("inputs", [])
                        if item.get("name")
                    }
                    for index, child_input in enumerate(self.subgraphs[source_type].get("inputs", [])):
                        # Hidden subgraph inputs (for example a seed) may be
                        # omitted from the parent node.  Their positions then
                        # differ, so wiring by index shifts every later input.
                        parent_input = parent_inputs.get(child_input.get("name"), {})
                        parent_link = parent_input.get("link")
                        child_bindings[index] = source_for_link(parent_link)
                    child_path = self._node_id(path, source_id)
                    child = self._expand(self.subgraphs[source_type], child_path, child_bindings)
                    expanded_children[source_id] = child
                return child.get(source_slot)
            return NodeOutput(self._node_id(path, source_id), source_slot)

        for node_id, node in nodes.items():
            if node_id in {input_node_id, output_node_id}:
                continue
            node_type = node.get("type")
            if node_type in self.subgraphs:
                # Expansion is lazy: it happens only when an output is consumed.
                continue
            if node_type in {"MarkdownNote", "PreviewImage", "MaskPreview"}:
                continue

            api_inputs: dict[str, Any] = {}
            linked_names: set[str] = set()
            for input_spec in node.get("inputs", []):
                name = input_spec.get("name")
                if not name:
                    continue
                source = source_for_link(input_spec.get("link"))
                if source is not None:
                    api_inputs[name] = [source.node_id, source.slot]
                    linked_names.add(name)

            required = self.object_info.get(node_type, {}).get("input", {}).get("required", {})
            values = self._widget_values(node)
            value_index = 0
            for name, input_config in required.items():
                # ``widgets_values`` keeps values for linked widgets too.  We
                # must consume those positions even though the API prompt uses
                # a graph link, otherwise every subsequent widget is shifted.
                if not self._uses_widget(input_config):
                    continue
                if value_index >= len(values):
                    continue
                value = values[value_index]
                value_index += 1
                while value_index < len(values) and values[value_index] in CONTROL_WIDGET_VALUES:
                    value_index += 1
                if name not in linked_names:
                    api_inputs[name] = value

            self.result[self._node_id(path, node_id)] = {
                "class_type": node_type,
                "inputs": api_inputs,
                "_meta": {"title": node.get("title") or node_type},
            }

        outputs: dict[int, NodeOutput | None] = {}
        # ComfyUI's current workflow JSON represents subgraph outputs outside
        # ``nodes``.  Each descriptor points back to the subgraph's virtual
        # output node through ``linkIds``.  Older exports still embed that node
        # in ``nodes``, so retain that form as a fallback.
        output_descriptors = graph.get("outputs")
        if isinstance(output_descriptors, list) and output_descriptors:
            for slot, descriptor in enumerate(output_descriptors):
                link_ids = descriptor.get("linkIds", [])
                if not isinstance(link_ids, list):
                    link_ids = [link_ids]
                link_id = next((link for link in link_ids if link is not None), None)
                outputs[slot] = source_for_link(link_id)
        else:
            output_node = nodes.get(output_node_id, {})
            for slot, output_input in enumerate(output_node.get("inputs", [])):
                outputs[slot] = source_for_link(output_input.get("link"))
        self.expanded_subgraphs[path] = outputs
        return outputs


def wait_for_comfyui() -> None:
    deadline = time.monotonic() + SERVER_START_TIMEOUT_SECONDS
    while time.monotonic() < deadline:
        try:
            if requests.get(f"{COMFY_URL}/", timeout=5).status_code == 200:
                return
        except requests.RequestException:
            pass
        time.sleep(2)
    raise RuntimeError("ComfyUI did not become ready before the startup timeout")


def ensure_sam3_checkpoint() -> None:
    destination = VOLUME_MODELS / "checkpoints" / SAM3_FILENAME
    if destination.is_file() and destination.stat().st_size > 0:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_suffix(".download")
    with requests.get(SAM3_URL, stream=True, timeout=(30, 600)) as response:
        response.raise_for_status()
        with partial.open("wb") as file:
            for chunk in response.iter_content(1024 * 1024):
                if chunk:
                    file.write(chunk)
    partial.replace(destination)


def download_video(url: str, job_id: str) -> str:
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError("input_url must be an absolute HTTP(S) URL")
    COMFY_INPUT.mkdir(parents=True, exist_ok=True)
    filename = f"runpod-{job_id}.mp4"
    destination = COMFY_INPUT / filename
    received = 0
    with requests.get(url, stream=True, timeout=(30, 600)) as response:
        response.raise_for_status()
        with destination.open("wb") as file:
            for chunk in response.iter_content(1024 * 1024):
                if not chunk:
                    continue
                received += len(chunk)
                if received > MAX_INPUT_BYTES:
                    raise ValueError("input video exceeds the 100 MiB worker limit")
                file.write(chunk)
    if not received:
        raise ValueError("input video is empty")
    return filename


def build_prompt(prompt: str, input_filename: str) -> dict[str, Any]:
    ui_workflow = json.loads(WORKFLOW_PATH.read_text(encoding="utf-8"))
    object_info = requests.get(f"{COMFY_URL}/object_info", timeout=30).json()
    workflow = WorkflowFlattener(ui_workflow, object_info).flatten()

    # The official workflow's defaults are suitable for the first acceptance
    # test once we replace the demo media and prompt.  A 49-frame, 640px test
    # keeps the first live run within a conservative A100 memory budget.
    # LoadVideo takes a filename from ComfyUI's input directory.  Its output is
    # the VIDEO object wired into the VACE subgraph; assigning the filename to
    # a downstream ``video`` input turns it into a raw string instead.
    workflow["209"]["inputs"]["file"] = input_filename
    workflow["209"]["inputs"].pop("video", None)
    workflow["306/280"]["inputs"]["text"] = prompt
    workflow["306/268/237"]["inputs"]["text"] = "dress"
    workflow["306/289"]["inputs"]["length"] = 49
    workflow["306/290"]["inputs"]["value"] = 640
    workflow["306/297"]["inputs"]["value"] = 640
    workflow["306/300"]["inputs"]["value"] = False

    # ``ResizeImageMaskNode`` is a composite ComfyUI control.  The prompt API
    # needs its selected DynamicCombo parent plus namespaced child values; the
    # generic widget mapper only sees the child fields.  Pin the selection and
    # its crop option explicitly.  Width and height remain linked to the
    # workflow's calculated 640px values above.
    resize_inputs = workflow["306/293"]["inputs"]
    resize_inputs["resize_type"] = "scale dimensions"
    resize_inputs["resize_type.crop"] = "center"
    resize_inputs["scale_method"] = "area"
    resize_inputs.pop("crop", None)

    # The workflow export predates ComfyUI's required codec input.  API prompts
    # do not inherit UI defaults, so make the documented "auto" choice explicit.
    workflow["69"]["inputs"]["codec"] = "auto"

    # The network volume deliberately does not contain the optional Lightning
    # LoRA.  Bypass it entirely instead of merely toggling a UI switch.
    workflow["306/266"]["inputs"]["model"] = ["306/299", 0]
    workflow.pop("306/272", None)
    workflow.pop("306/275", None)

    # Reference image is optional; the template's bundled demo image is not
    # available in the serverless input directory.
    workflow["306/281"]["inputs"].pop("reference_image", None)
    return workflow


def queue_prompt(workflow: dict[str, Any]) -> str:
    response = requests.post(
        f"{COMFY_URL}/prompt",
        json={"prompt": workflow, "client_id": str(uuid.uuid4())},
        timeout=60,
    )
    if response.status_code >= 400:
        raise RuntimeError(f"ComfyUI rejected the workflow: {response.text}")
    prompt_id = response.json().get("prompt_id")
    if not prompt_id:
        raise RuntimeError("ComfyUI did not return a prompt ID")
    return prompt_id


def wait_for_history(prompt_id: str) -> dict[str, Any]:
    deadline = time.monotonic() + EXECUTION_TIMEOUT_SECONDS
    while time.monotonic() < deadline:
        response = requests.get(f"{COMFY_URL}/history/{prompt_id}", timeout=30)
        response.raise_for_status()
        history = response.json().get(prompt_id)
        if history:
            outputs = history.get("outputs") or {}
            if outputs:
                return history
            status = history.get("status") or {}
            if status.get("completed") or status.get("status_str") in {"error", "failed"}:
                messages = status.get("messages") or []
                detail = messages[-1] if messages else "no output was produced"
                raise RuntimeError(
                    "ComfyUI execution failed: "
                    + json.dumps(detail, ensure_ascii=False)
                )
        time.sleep(2)
    raise TimeoutError("VACE workflow exceeded the execution timeout")


def video_from_history(history: dict[str, Any]) -> dict[str, str]:
    candidates: list[dict[str, Any]] = []
    for node_output in history.get("outputs", {}).values():
        for key in ("videos", "gifs", "images"):
            candidates.extend(node_output.get(key, []))
    for item in candidates:
        filename = item.get("filename", "")
        if not filename.lower().endswith((".mp4", ".webm", ".mov")):
            continue
        params = {
            "filename": filename,
            "subfolder": item.get("subfolder", ""),
            "type": item.get("type", "output"),
        }
        response = requests.get(f"{COMFY_URL}/view", params=params, timeout=300)
        response.raise_for_status()
        content_type = "video/webm" if filename.lower().endswith(".webm") else "video/mp4"
        return {
            "data": base64.b64encode(response.content).decode("ascii"),
            "filename": filename,
            "content_type": content_type,
        }
    raise RuntimeError("ComfyUI finished without a video output")


def handler(job: dict[str, Any]) -> dict[str, Any]:
    data = job.get("input") or {}
    prompt = data.get("prompt")
    input_url = data.get("input_url")
    if not isinstance(prompt, str) or not prompt.strip():
        return {"error": "prompt is required"}
    if not isinstance(input_url, str):
        return {"error": "input_url is required"}

    job_id = str(job.get("id") or uuid.uuid4())
    input_file = COMFY_INPUT / f"runpod-{job_id}.mp4"
    try:
        wait_for_comfyui()
        ensure_sam3_checkpoint()
        filename = download_video(input_url, job_id)
        prompt_id = queue_prompt(build_prompt(prompt.strip(), filename))
        return {"video": video_from_history(wait_for_history(prompt_id))}
    except Exception as error:  # RunPod expects structured handler errors.
        return {"error": str(error)}
    finally:
        input_file.unlink(missing_ok=True)


if __name__ == "__main__":
    runpod.serverless.start({"handler": handler})
